Verdictd: download rats-tls by gitclone
inclavare-containers/verdictd pull request #2
Opened 2022-02-14 02:31 UTC by liangzhou121

Signed-off-by: Zhou Liang <liang.a.zhou@linux.alibaba.com>

2022-02-14 02:35 UTC, jiazhang0 commented on Makefile
> +RatsTLS_srcdir := $(CUR_DIR)/rats-tls
Use Rats_Tls_Src_Dir instead, which suits for your variable naming style in this Makefile.

2022-02-14 02:37 UTC, jiazhang0 requested changes

2022-02-14 02:37 UTC, jiazhang0 commented on Makefile
> +RatsTLS:
rename to "build_rats_tls".

2022-02-14 02:37 UTC, jiazhang0 commented on Makefile
>  .PHONY: all
Add "build_rats_tls" to .PHONY.

2022-02-14 02:42 UTC, haosanzi commented on Makefile
> +	@rm -fr $(RatsTLS_srcdir)
The `/usr/share/rats-tls/` and /usr/local/lib/rats-tls` also should uninstalled

2022-02-14 03:02 UTC, haosanzi approved these changes

2022-02-14 05:52 UTC, jiazhang0 commented on Makefile
> +	@rm -fr $(Rats_Tls_Src_Dir)
I think you can preserve the source code of rats-tls. Instead, use distclean rule to delete rats-tls:

.PHONY: all clean distclean build_rats_tls

distclean:
   $(MAKE) clean
   @rm -fr $(Rats_Tls_Src_Dir)

2022-02-15 02:20 UTC, merged

2022-02-15 02:20 UTC, jiazhang0 commented on Makefile
> +.PHONY: all build_rats_tls distclean
Forget to add `clean`.